load("//engine/build:isaac.bzl", "isaac_cc_module")

    filegroup(name = "universal_robots_resources",
              data =
                  [
                    "ur_robot_driver/resources/ros_control.urscript",
                    "ur_robot_driver/resources/rtde_input_recipe.txt",
                    "ur_robot_driver/resources/rtde_output_recipe.txt",
                  ],
              visibility = ["//visibility:public"], )

        isaac_cc_module(name = "universal_robots",
                        srcs =
                            [
                              "UniversalRobots.cpp",
                              "ur_robot_driver/src/comm/server.cpp",
                              "ur_robot_driver/src/comm/tcp_socket.cpp",
                              "ur_robot_driver/src/primary/primary_package.cpp",
                              "ur_robot_driver/src/primary/robot_message.cpp",
                              "ur_robot_driver/src/primary/robot_message/version_message.cpp",
                              "ur_robot_driver/src/primary/robot_state/kinematics_info.cpp",
                              "ur_robot_driver/src/rtde/control_package_pause.cpp",
                              "ur_robot_driver/src/rtde/control_package_setup_inputs.cpp",
                              "ur_robot_driver/src/rtde/control_package_setup_outputs.cpp",
                              "ur_robot_driver/src/rtde/control_package_start.cpp",
                              "ur_robot_driver/src/rtde/data_package.cpp",
                              "ur_robot_driver/src/rtde/get_urcontrol_version.cpp",
                              "ur_robot_driver/src/rtde/request_protocol_version.cpp",
                              "ur_robot_driver/src/rtde/rtde_client.cpp",
                              "ur_robot_driver/src/rtde/rtde_package.cpp",
                              "ur_robot_driver/src/rtde/rtde_writer.cpp",
                              "ur_robot_driver/src/rtde/text_message.cpp",
                              "ur_robot_driver/src/ur/calibration_checker.cpp",
                              "ur_robot_driver/src/ur/dashboard_client.cpp",
                              "ur_robot_driver/src/ur/tool_communication.cpp",
                              "ur_robot_driver/src/ur/ur_driver.cpp",
                            ],
                        hdrs =
                            [
                              "UniversalRobots.hpp",
                              "ur_robot_driver/include/ur_robot_driver/comm/bin_parser.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/package.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/package_serializer.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/parser.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/pipeline.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/producer.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/reverse_interface.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/script_sender.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/server.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/shell_consumer.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/stream.h",
                              "ur_robot_driver/include/ur_robot_driver/comm/tcp_socket.h",
                              "ur_robot_driver/include/ur_robot_driver/exceptions.h",
                              "ur_robot_driver/include/ur_robot_driver/log.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/package_header.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/primary_package.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/primary_parser.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/robot_message.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/robot_message/version_message.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/robot_state.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/robot_state/kinematics_info.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/robot_state/master_board.h",
                              "ur_robot_driver/include/ur_robot_driver/primary/robot_state/robot_mode_data.h",
                              "ur_robot_driver/include/ur_robot_driver/queue/atomicops.h",
                              "ur_robot_driver/include/ur_robot_driver/queue/readerwriterqueue.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/control_package_pause.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/control_package_setup_inputs.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/control_package_setup_outputs.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/control_package_start.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/data_package.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/get_urcontrol_version.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/package_header.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/request_protocol_version.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/rtde_client.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/rtde_package.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/rtde_parser.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/rtde_writer.h",
                              "ur_robot_driver/include/ur_robot_driver/rtde/text_message.h",
                              "ur_robot_driver/include/ur_robot_driver/types.h",
                              "ur_robot_driver/include/ur_robot_driver/ur/calibration_checker.h",
                              "ur_robot_driver/include/ur_robot_driver/ur/dashboard_client.h",
                              "ur_robot_driver/include/ur_robot_driver/ur/datatypes.h",
                              "ur_robot_driver/include/ur_robot_driver/ur/tool_communication.h",
                              "ur_robot_driver/include/ur_robot_driver/ur/ur_driver.h",
                              "ur_robot_driver/include/ur_robot_driver/ur/version_information.h",
                            ],
                        copts = ["-Ipackages/universal_robots/ur_robot_driver/include"],
                        data = ["//packages/universal_robots:universal_robots_resources"], defines = ["BAZEL_BUILD"],
                        visibility = ["//visibility:public"], deps = [
                          "//engine/gems/kinematic_tree",
                          "//packages/composite/gems:parser",
                          "//packages/map:kinematic_tree",
                          "@boost//:variant",
                        ], )
