load("//bzl:module.bzl", "isaac_subgraph")

isaac_subgraph(
    name = "ur3_subgraph",
    modules = [
        "//packages/universal_robots:universal_robots",
        "map",
        "planner",
        "lqr",
		"//packages/universal_robots/ur_controller:ur_controller"
    ],
	data = [
		"//packages/universal_robots/ur_robot_driver/config"
	],
    subgraph = "ur3.subgraph.json",
    visibility = ["//visibility:public"]
)

isaac_subgraph(
    name = "ur5_subgraph",
    modules = [
        "//packages/universal_robots:universal_robots",
        "map",
        "planner",
        "lqr",
		"//packages/universal_robots/ur_controller:ur_controller"
    ],
	data = [
		"//packages/universal_robots/ur_robot_driver/config"
	],
    subgraph = "ur5.subgraph.json",
    visibility = ["//visibility:public"]
)

isaac_subgraph(
    name = "ur10_subgraph",
    modules = [
        "//packages/universal_robots:universal_robots",
        "map",
        "planner",
        "lqr",
		"//packages/universal_robots/ur_controller:ur_controller"
    ],
	data = [
		"//packages/universal_robots/ur_robot_driver/config",
	],
    subgraph = "ur10.subgraph.json",
    visibility = ["//visibility:public"]
)

isaac_subgraph(
    name = "ur3e_subgraph",
    modules = [
        "//packages/universal_robots:universal_robots",
        "map",
        "planner",
        "lqr",
		"//packages/universal_robots/ur_controller:ur_controller"
    ],
	data = [
		"//packages/universal_robots/ur_robot_driver/config"
	],
    subgraph = "ur3e.subgraph.json",
    visibility = ["//visibility:public"]
)

isaac_subgraph(
    name = "ur5e_subgraph",
    modules = [
        "//packages/universal_robots:universal_robots",
        "map",
        "planner",
        "lqr",
		"//packages/universal_robots/ur_controller:ur_controller"
    ],
	data = [
		"//packages/universal_robots/ur_robot_driver/config"
	],
    subgraph = "ur5e.subgraph.json",
    visibility = ["//visibility:public"]
)

isaac_subgraph(
    name = "ur10e_subgraph",
    modules = [
        "//packages/universal_robots:universal_robots",
        "map",
        "planner",
        "lqr",
		"//packages/universal_robots/ur_controller:ur_controller"
    ],
	data = [
		"//packages/universal_robots/ur_robot_driver/config"
	],
    subgraph = "ur10e.subgraph.json",
    visibility = ["//visibility:public"]
)

isaac_subgraph(
    name = "ur16e_subgraph",
    modules = [
        "//packages/universal_robots:universal_robots",
        "map",
        "planner",
        "lqr",
		"//packages/universal_robots/ur_controller:ur_controller"
    ],
	data = [
		"//packages/universal_robots/ur_robot_driver/config"
	],
    subgraph = "ur16e.subgraph.json",
    visibility = ["//visibility:public"]
)
