py_test(
	name = "tool_io_test",
	srcs = ["tool_io_test.py"],
	data = [
		"//packages/universal_robots/ur_robot_driver/apps:ur_eseries_robot_subgraph",
		"//packages/universal_robots/ur_robot_driver/apps:ur_cb3_robot_subgraph",
		"utils/ur_msg.py",
		"utils/test_utils.py"
	],
	tags = ["pytest"],
	deps = [
		"//packages/pyalice",
	],
)

py_test(
	name = "trajectory_test",
	srcs = ["trajectory_test.py"],
	data = [
		"//packages/universal_robots/ur_robot_driver/apps:ur_eseries_robot_subgraph",
		"//packages/universal_robots/ur_robot_driver/apps:ur_cb3_robot_subgraph",
		"utils/ur_msg.py",
		"utils/test_utils.py"
	],
	tags = ["pytest"],
	deps = [
		"//packages/pyalice",
	],
)

py_test(
	name = "scaled_trajectory_test",
	srcs = ["scaled_trajectory_test.py"],
	data = [
		"//packages/universal_robots/ur_robot_driver/apps:ur_eseries_robot_subgraph",
		"//packages/universal_robots/ur_robot_driver/apps:ur_cb3_robot_subgraph",
		"utils/ur_msg.py",
		"utils/test_utils.py"
	],
	tags = ["pytest"],
	deps = [
		"//packages/pyalice",
	],
)

py_test(
	name = "external_control_test",
	srcs = ["external_control_test.py"],
	data = [
		"//packages/universal_robots/ur_robot_driver/apps:ur_eseries_robot_subgraph",
		"//packages/universal_robots/ur_robot_driver/apps:ur_cb3_robot_subgraph",
		"utils/ur_msg.py",
		"utils/test_utils.py"
	],
	tags = ["pytest"],
	deps = [
		"//packages/pyalice",
	],
)