filegroup(
    name = "config",
    srcs = [
        "ur3.kinematic.json",
        "ur5.kinematic.json",
        "ur10.kinematic.json",
        "ur3e.kinematic.json",
        "ur5e.kinematic.json",
        "ur10e.kinematic.json",
        "ur16e.kinematic.json"
    ],
    visibility = ["//visibility:public"],
)
